/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "IP_Address": {                                   "en": "IP address of Wiim device",                        "de": "IP Adresse des Wiim Geräts",                       "ru": "IP address of Wiim device",                        "pt": "IP address of Wiim device",                        "nl": "IP address of Wiim device",                        "fr": "IP address of Wiim device",                        "it": "IP address of Wiim device",                        "es": "IP address of Wiim device",                        "pl": "IP address of Wiim device",                        "uk": "IP-адреса пристрою Wiim",                          "zh-cn": "IP address of Wiim device"},
    "Refresh_Interval": {                             "en": "interval for refresh of player data in seconds",   "de": "Interval für die Aktualisierung der Player Daten in Sekuden", "ru": "interval for refresh of player data in seconds",   "pt": "interval for refresh of player data in seconds",   "nl": "interval for refresh of player data in seconds",   "fr": "interval for refresh of player data in seconds",   "it": "interval for refresh of player data in seconds",   "es": "interval for refresh of player data in seconds",   "pl": "interval for refresh of player data in seconds",   "uk": "інтервал оновлення даних гравця в секундах",       "zh-cn": "interval for refresh of player data in seconds"},
    "wiim adapter settings": {                        "en": "Adapter settings for wiim",                        "de": "Adaptereinstellungen für wiim",                    "ru": "Настройки адаптера для wiim",                      "pt": "Configurações do adaptador para wiim",             "nl": "Adapterinstellingen voor wiim",                    "fr": "Paramètres d'adaptateur pour wiim",                "it": "Impostazioni dell'adattatore per wiim",            "es": "Ajustes del adaptador para wiim",                  "pl": "Ustawienia adaptera dla wiim",                     "uk": "Налаштування адаптера для wiim",                   "zh-cn": "wiim的适配器设置"},
};