/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Refresh_Interval": {                             "en": "interval for refresh of player data in seconds",   "de": "Intervall für die Aktualisierung der Streamerdaten in Sekunden",   "ru": "интервал для обновления данных игрока в секундах",   "pt": "intervalo para atualização de dados do jogador em segundos",   "nl": "interval voor het vernieuwen van spelergegevens in seconden",   "fr": "intervalle pour rafraîchir les données du lecteur en secondes",   "it": "intervallo per aggiornamento dei dati del giocatore in secondi",   "es": "intervalo para la actualización de los datos del reproductor en segundos",   "pl": "interwał odświeżania danych gracza w sekundach",   "uk": "інтервал для оновлення даних гравця за секундами",   "zh-cn": "玩家数据刷新间隔( 秒)"},
};